#!/usr/bin/env Rscript
# -*- coding: utf-8 -*-
# @Time    : 2022/03/24
# @Author  : zhangsiwen
# @contact : zhang.siwen@puruijizhun.com
# @LastModified: 2022/03/24
# @ChangeLog
#     20220324, first version


# test if there is at least one argument: if not, return an error
args = commandArgs(trailingOnly=TRUE)
if (length(args)==0) {
  stop("\nUsage:
  Rscript --vanilla mutation_signal_compare.r -h
  Rscript --vanilla mutation_signal_compare.r --in1 tissue.count --in2 plasma.count --name1 Tissue --name2 Plasma --out prefix
  ", call.=FALSE)
}


library(optparse, quietly=TRUE)
library(ggplot2, quietly=TRUE)
library(ggalt, quietly=TRUE)
theme_set(theme_classic())
library(dplyr, quietly=TRUE)


# define arguments
option_list = list(
  make_option("--in1", type="character", default=NULL, help="tsv file generated by readcount_extraction.py", metavar="character"),
  make_option("--in2", type="character", default=NULL, help="tsv file generated by readcount_extraction.py", metavar="character"),
  make_option("--name1", type="character", default=NULL, help="sample name of infile 1", metavar="character"),
  make_option("--name2", type="character", default=NULL, help="sample name of infile 2", metavar="character"),
  make_option("--out", type="character", default=NULL, help="output prefix name", metavar="character")
);

opt_parser = OptionParser(option_list=option_list)
opt = parse_args(opt_parser)


if (FALSE) {
  df1 <- read.table('P120.bam-readcount.idt.tissue_signal', sep = '\t', header = T, row.names = 1)
  df2 <- read.table('P120.bam-readcount.idt.plasma_signal', sep = '\t', header = T, row.names = 1, fill = NA)
  name1 <- 'Tissue'
  name2 <- 'Plasma'
  out <- 'P120.test'
}


df1 <- read.table(opt$in1, sep = '\t', header = T, row.names = 1)
df2 <- read.table(opt$in2, sep = '\t', header = T, row.names = 1, fill = NA)
name1 <- opt$name1
name2 <- opt$name2
out <- opt$out

df1$Type <- name1
df1$Mutations <- rownames(df1)
# add '-' for descending ranks
df1$Rank <- rank(-df1$sample, ties.method="min")
df2$Type <- name2
df2$Mutations <- rownames(df2)
df2$Rank <- rank(-df2$sample, ties.method="min")


# density plot
rbindDf <- rbind(df1, df2)
pdf(paste0(out,'.density.pdf'), width = 12, height = 12)
ggplot(rbindDf) + 
  geom_density(aes(x=sample, y=..scaled.., color=Type, fill=Type), alpha=0.6) + 
  labs(title=paste('Frequency of',name1,'vs',name2, sep=' '), caption=out, x="Frequency", y="Density") + 
  theme(axis.text=element_text(size=30), axis.title=element_text(size=30),plot.title=element_text(size=40), legend.title=element_text(size=30), legend.text=element_text(size=30), plot.caption=element_text(size=20))
dev.off()


# slope plot
cbindDf <- cbind(df1, df2)
colnames(cbindDf) <- c(paste(name1,colnames(df1), sep='.'), paste(name2,colnames(df2), sep='.'))
rank1 <- paste0(name1,'.Rank')
rank2 <- paste0(name2,'.Rank')
cbindDf$RankChange <- ifelse(cbindDf[,rank1]-cbindDf[,rank2] < 0|cbindDf[,paste0(name2,'.sample')] == 0, "green", ifelse(cbindDf[,rank1]-cbindDf[,rank2] == 0, "grey", "red"))

pdf(paste0(out,'.rankslope.pdf'), width = 12, height = 12)
ggplot(cbindDf) + geom_segment(aes_string(x=1, xend=2, y=paste0(name1,'.sample'), yend=paste0(name2,'.sample'), col='RankChange'), size=.75, show.legend=T) + 
  geom_vline(xintercept=1, linetype="dashed", size=.1, alpha=0.6) + 
  geom_vline(xintercept=2, linetype="dashed", size=.1, alpha=0.6) +
  geom_hline(yintercept=0, linetype="dashed", size=.1, alpha=0.6) + 
  scale_color_manual(labels = c("Up", "Equal", "Down"), values = c("red"="#f8766d", "grey"="#808080", "green"="#00ba38")) +  # color of lines
  labs(title=paste('Rank change of',name1,'vs',name2, sep=' '), caption=out, x='Type', y='Frequency') +
  xlim(.8, 2.2) + scale_x_continuous(breaks=c(1,2), labels=c(name1, name2)) + 
  theme(axis.text=element_text(size=30), axis.title=element_text(size=30),plot.title=element_text(size=40), legend.title=element_text(size=30), legend.text=element_text(size=30), plot.caption=element_text(size=20))
dev.off()


# dumbbell plot
cbindDf <- cbindDf[order(cbindDf[,paste0(name2,'.Rank')], cbindDf[,paste0(name1,'.Rank')]),]
cbindDf[,paste0(name1,'.Mutations')] <- factor(cbindDf[,paste0(name1,'.Mutations')], levels=as.character(cbindDf[,paste0(name1,'.Mutations')])) 

pdf(paste0(out,'.dumbbell.pdf'), width = 20, height = 20)
ggplot(cbindDf, aes_string(x=paste0(name1,'.sample'), xend=paste0(name2,'.sample'), y=paste0(name1,'.Mutations'), group=paste0(name1,'.Mutations'))) + 
  geom_dumbbell(colour_x="#CCE5FF", color="#a3c4dc", size=2, colour_xend="#0e668b") + 
  labs(x="Frequency", y="Mutations", 
       title=paste('Frequency change of',name1,'vs',name2, sep=' '), caption=out) +
  theme(plot.title = element_text(hjust=0.5, face="bold"),
        panel.border=element_blank()) + 
  theme(axis.text=element_text(size=15), axis.title=element_text(size=20),plot.title=element_text(size=30), legend.title=element_text(size=20), legend.text=element_text(size=20), plot.caption=element_text(size=20))
dev.off()


# stats and wilcox test
stats <- data.frame(group_by(rbindDf, Type) %>%
  summarise(
    count = n(),
    median = median(sample, na.rm = TRUE),
    IQR = IQR(sample, na.rm = TRUE)
  ))
res <- wilcox.test(cbindDf[,paste0(name1,'.Rank')], cbindDf[,paste0(name2,'.Rank')], exact = FALSE)
stats$wilcox.Pvalue <- res$p.value
write.table(stats, paste0(out,'.stats.tsv'), quote=F, sep='\t', row.names=F)
write.table(cbindDf, paste0(out,'.cbind.tsv'), quote=F, sep='\t', row.names=F)

