#!/usr/bin/env Rscript
# -*- coding: utf-8 -*-
# @Time    : 2022/07/25
# @Author  : zhangsiwen
# @contact : zhang.siwen
# @LastModified: 2022/07/25
# @ChangeLog
#     20220725, first version


# test if there is at least one argument: if not, return an error
args = commandArgs(trailingOnly=TRUE)
if (length(args)==0) {
  stop("\nUsage:
  Rscript --vanilla check_target_cov.r -h
  Rscript --vanilla check_target_cov.r --in per_target_cov --out outprefix --dir ./
  ", call.=FALSE)
}


library(optparse, quietly=TRUE)
library(ggplot2, quietly=TRUE)
library(ggpubr, quietly=TRUE)
theme_set(theme_classic())
library(dplyr, quietly=TRUE)
library(data.table, quietly=TRUE)
library(RColorBrewer, quietly=TRUE)
library(ggpmisc, quietly=TRUE)


# define arguments
option_list = list(
  make_option("--in", type="character", default=NULL, help="per_target_cov tsv file generated by picard CollectTargetedPcrMetrics", metavar="character"),
  make_option("--bed", type="character", default=NULL, help="targets in bed format", metavar="character"),
  make_option("--out", type="character", default=NULL, help="output prefix", metavar="character"),
  make_option("--dir", type="character", default='./', help="output outdir, default current path", metavar="character")
);

opt_parser = OptionParser(option_list=option_list)
opt = parse_args(opt_parser)


if (FALSE) {
  df <- read.table('P11.per_target_cov.tsv', sep = '\t', header = T)
  bed <- read.table('../PRJZ220626A_p11_ROI.bed', sep = '\t', header = T)
  out <- 'P11'
  dir <- './'
}


df <- read.table(opt$in, sep = '\t', header = T)
out <- opt$out
if (opt$dir != './') {
  dir.create(file.path(dir), showWarnings = FALSE)
  out <- paste(dir, out, sep='/')
}


# GC content VS mean coverage (correlation)

pdf(paste0(out,'.gc_content_vs_mean_coverage.pdf'), width = 6, height = 6)
ggplot(df, aes(x=X.gc, y=mean_coverage)) + 
  geom_point() + geom_rug() + #geom_density_2d() +
  #geom_smooth(method='loess', se=TRUE, fullrange=TRUE, level=0.95, color="red") +
  #stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")), 
  #         method = "spearman", label.x = 0, label.y = max(df$mean_coverage), size=5) + 
  geom_smooth(method='glm', formula = y ~ x + I(x^2), 
              se=TRUE, fullrange=TRUE, level=0.95, color="blue") +
  stat_poly_line(formula = y ~ x + I(x^2)) +
  stat_poly_eq(formula = y ~ x + I(x^2), size=4, 
               aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep="~`,`~"))) +
  #stat_regline_equation(label.x = 0, label.y = max(df$mean_coverage), size=5) + 
  #stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")), 
  #         method = "spearman", label.x = 0, label.y = max(df$mean_coverage)*0.9, size=5) + 
  labs(title='GC content VS target mean coverage', caption='Method: glm-spearman',
       x='GC content', y='Target mean coverage') +
  xlim(0, 1) + ylim(0,max(df$mean_coverage)) +
  scale_color_brewer(palette="Set2") + scale_fill_brewer(palette="Set2") +
  theme(axis.text=element_text(size=15), axis.title=element_text(size=15), 
        plot.title=element_text(size=20), plot.caption=element_text(size=15), 
        legend.title=element_text(size=15), legend.text=element_text(size=15))
dev.off()



# coverage boxplot

mat <- melt(df, id.vars=c('chrom','start','end','name'), measure.vars=c('min_coverage', 'mean_coverage', 'max_coverage'))
mat$variable <- rep(c('Min coverage', 'Mean coverage', 'Max coverage'), each=dim(df)[1])
mins <- mat %>% group_by(variable) %>% summarise_at(vars(value), list(name = min))
means <- mat %>% group_by(variable) %>% summarise_at(vars(value), list(name = mean))
medians <- mat %>% group_by(variable) %>% summarise_at(vars(value), list(name = median))
maxs <- mat %>% group_by(variable) %>% summarise_at(vars(value), list(name = max))
stats <- data.frame(mins, medians, means, maxs)[,c(1,2,4,6,8)]
colnames(stats) <- c('variable', 'Min', 'Median','Mean', 'Max')
stats <- stats %>% mutate_if(is.numeric, round)

pdf(paste0(out,'.coverages_boxplot.pdf'), width = 6, height = 6)
ggplot(mat, aes(x=variable, y=value, color=variable, fill=variable)) +
  geom_boxplot(alpha=0.5, outlier.color=NA) + geom_jitter(shape=16, position=position_jitter(0.2), size=2) + 
  geom_text(data = stats, aes(x = variable, y = Min, label = paste('Min:',Min)), size = 4, color='black') + 
  geom_text(data = stats, aes(x = variable, y = Median, label = paste('Median:',Median)), size = 4, color='black') + 
  geom_text(data = stats, aes(x = variable, y = Mean, label = paste('Mean:',Mean)), size = 4, color='black') + 
  geom_text(data = stats, aes(x = variable, y = Max, label = paste('Max:',Max)), size = 4, color='black') + 
  labs(title='Coverage', x='Groups', y='Coverages') + 
  scale_color_brewer(palette="Set2") + scale_fill_brewer(palette="Set2") +
  theme(axis.text=element_text(size=10), axis.title=element_text(size=10), 
      plot.title=element_text(size=15), plot.caption=element_text(size=10), 
      legend.title=element_text(size=10), legend.text=element_text(size=10))
dev.off()



# ROI length boxplot

bed <- read.table(opt$bed, sep = '\t', header = T)

bed$ROI <- 'Targets'
bed$Size <- bed[,3] - bed[,2]
Min <- min(bed$Size)
Median <- round(median(bed$Size))
Mean <- round(mean(bed$Size))
Max <- max(bed$Size)

pdf(paste0(out,'.ROI_size_boxplot.pdf'), width = 4, height = 6)
ggplot(bed, aes(x=ROI, y=Size, color=ROI, fill=ROI)) +
  geom_violin(alpha=0.5) + 
  geom_boxplot(alpha=0.5, width = .2, outlier.color=NA) + 
  geom_jitter(shape=16, position=position_jitter(0.2), size=2) + 
  geom_text(aes(x=ROI, y = Min, label = paste('Min:',Min)), size = 4, color='black') + 
  geom_text(aes(x=ROI, y = Median, label = paste('Median:',Median)), size = 4, color='black') + 
  geom_text(aes(x=ROI, y = Mean, label = paste('Mean:',Mean)), size = 4, color='black') + 
  geom_text(aes(x=ROI, y = Max, label = paste('Max:',Max)), size = 4, color='black') + 
  labs(title='Target Size Distribution', x='', y='Size (bp)') + 
  scale_color_brewer(palette="Set2") + scale_fill_brewer(palette="Set2") +
  theme(axis.text=element_text(size=10), axis.title=element_text(size=10), 
        plot.title=element_text(size=15), plot.caption=element_text(size=10),
        legend.position="none")
dev.off()

