#!/usr/bin/env Rscript
# -*- coding: utf-8 -*-
# @Time    : 2022/02/14
# @Author  : zhangsiwen
# @contact : zhang.siwen@puruijizhun.com
# @LastModified: 2022/02/14
# @ChangeLog
#     20220214, first version
#     20220323, minor change, mkdir outdir


# test if there is at least one argument: if not, return an error
args = commandArgs(trailingOnly=TRUE)
if (length(args)==0) {
  stop("\nUsage:
  Rscript --vanilla ascat_cnv.r -h
  Rscript --vanilla ascat_cnv.r --somaticcnv somatic.cnv.logR --somaticbaf somatic.baf.tsv --germlinecnv germline.cnv.logR --germlinebaf germline.baf.tsv --out outprefix --outdir /path/
  ", call.=FALSE)
}


# install libraries
if (!require("optparse", quietly = TRUE)) {
    install.packages("BiocManager", lib = .libPaths()[1])
    BiocManager::install("optparse", lib = .libPaths()[1])
}
if (!require("ASCAT", quietly = TRUE)) {
    #install.packages('devtools')
    devtools::install_github("ASCAT", lib = .libPaths()[1])
    #install.packages("/mnt/ddngs/zhangsw/software/ascat-master/ASCAT.tar.gz", repo=NULL, type = "source")
}


# load libraries
library(optparse, quietly=TRUE)
library(ASCAT, quietly=TRUE)


# define arguments
option_list = list(
    make_option("--somaticcnv", type="character", default=NULL, help="cnv logR file generated by extract_mutation_cnv.py", metavar="character"),
    make_option("--somaticbaf", type="character", default=NULL, help="baf file generated by calculate_baf_platypus.py", metavar="character"),
    make_option("--germlinecnv", type="character", default=NULL, help="cnv logR file generated by extract_mutation_cnv.py", metavar="character"),
    make_option("--germlinebaf", type="character", default=NULL, help="baf file generated by calculate_baf_platypus.py", metavar="character"),
    make_option("--out", type="character", default=NULL, help="output prefix name", metavar="character"),
    make_option("--outdir", type="character", default=NULL, help="output file path", metavar="character")
);

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);


#ascat.bc <- ascat.loadData(Tumor_LogR_file='P13.varscanCopynumber.called.logR.tsv', Tumor_BAF_file='test.tumor.platypus.baf.tsv', Germline_LogR_file='P13.normal.logR.tsv', Germline_BAF_file='P13.normal.platypus.baf.tsv', chrs = c(1:22,"X", "Y"), gender = NULL, sexchromosomes = c("X", "Y"))
#ascat.plotRawData(ascat.bc, img.dir = './', img.prefix = 'test')
#ascat.bc <- ascat.aspcf(ascat.bc, out.dir = ".", out.prefix = "testt")
#ascat.plotSegmentedData(ascat.bc, img.dir = './', img.prefix = 'testtt')
#ascat.output <- ascat.runAscat(ascat.bc, gamma = 1, pdfPlot = T, y_limit = 5, circos = NA,  rho_manual = NA, psi_manual = NA, img.dir = './', img.prefix = 'testttt')
#cnvResult <- data.frame(ascat.output$segments_raw, 'ploidy'=ascat.output$ploidy, 'ACF'=ascat.output$aberrantcellfraction, 'goodnessOfFit'=ascat.output$goodnessOfFit, 'psi'=ascat.output$psi)
#cnvResult$cnTotal <- cnvResult$nMajor + cnvResult$nMinor
#write.table(cnvResult, 'testtttt', sep = '\t', row.names = FALSE, col.names = TRUE, quote = FALSE)


# output dir
dir.create(opt$outdir, warn.conflicts = FALSE, showWarnings = FALSE)


# ascat process
ascat.bc <- ascat.loadData(Tumor_LogR_file=opt$somaticcnv, 
    Tumor_BAF_file=opt$somaticbaf, 
    Germline_LogR_file=opt$germlinecnv, 
    Germline_BAF_file=opt$germlinebaf, 
    chrs = c(1:22,"X", "Y"), 
    gender = NULL, 
    sexchromosomes = c("X", "Y")
    )

ascat.plotRawData(ascat.bc, img.dir = opt$outdir, img.prefix = opt$out)

# run ASPCF segmentation
ascat.bc <- ascat.aspcf(ascat.bc, out.dir = opt$outdir, out.prefix = opt$out)
ascat.plotSegmentedData(ascat.bc, img.dir = opt$outdir, img.prefix = opt$out)

# calculate the allele-specific copy numbers
ascat.output <- ascat.runAscat(ascat.bc, gamma = 1, pdfPlot = T, y_limit = 5, circos = NA, 
    rho_manual = NA, psi_manual = NA, img.dir = opt$outdir, img.prefix = opt$out)

# create new CNV dataframe
cnvResult <- data.frame(ascat.output$segments_raw, 'ploidy'=ascat.output$ploidy, 'ACF'=ascat.output$aberrantcellfraction, 'goodnessOfFit'=ascat.output$goodnessOfFit, 'psi'=ascat.output$psi)
cnvResult$cnTotal <- cnvResult$nMajor + cnvResult$nMinor

# output
outname <- paste(opt$out, 'tsv', sep='.')
write.table(cnvResult, paste(opt$outdir, opt$out, sep='/'), sep = '\t', row.names = FALSE, col.names = TRUE, quote = FALSE)
